[package]
name = "wut_cursor"
version = "0.2.0"
edition = "2021"
description = "A lightweight iterator over a sequence of characters"
license = "MIT"
repository = "https://github.com/Refr900/wut_cursor"
readme = "README.md"
